const AlbumConstants = {
  ALBUMS_RECEIVED: "ALBUMS_RECEIVED",
  ALBUM_RECEIVED: "ALBUM_RECEIVED",
  ALBUM_WITH_PHOTOS_RECEIVED: "ALBUM_WITH_PHOTOS_RECEIVED",
  ALBUM_REMOVED: "ALBUM_REMOVED"
};

module.exports = AlbumConstants;
