const PhotoConstants = {
  PHOTOS_RECEIVED: "PHOTOS_RECEIVED",
  PHOTO_RECEIVED: "PHOTO_RECEIVED",
  PHOTO_REMOVED: "PHOTO_REMOVED",
  PHOTOS_REMOVED: "PHOTOS_REMOVED"
};

module.exports = PhotoConstants;
