# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b245fa6d491707e3251532f850aa9d937bb4442261ba77a6325f9af530b67a15a33b9011b2d28e584ec5bc57ddf67a7268e3fa5686840a62e44c45278e2d5f92

test:
  secret_key_base: 0c4c41e279a08d763cbfd555177180369e93d980f9c90d092803285c5a8c6bd5ab068c5f2654eab8ac21117cf43a005bbbb9b7a1be5cea645747be0887ea8166

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
